<?php

namespace ContainerI413iKI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S9s_MslService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S9s.msl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\LibroController::index' => ['privates', '.service_locator.Y09RE1E.App\\Controller\\LibroController::index()', 'getLibroControllerindexService', true],
            'App\\Controller\\LibroController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\LibroController::new()', 'getLibroControllernewService', true],
            'App\\Controller\\LibroController::show' => ['privates', '.service_locator.pXPo2Ij.App\\Controller\\LibroController::show()', 'getLibroControllershowService', true],
            'App\\Controller\\LibroController::edit' => ['privates', '.service_locator.8IPZHA6.App\\Controller\\LibroController::edit()', 'getLibroControllereditService', true],
            'App\\Controller\\LibroController::delete' => ['privates', '.service_locator.8IPZHA6.App\\Controller\\LibroController::delete()', 'getLibroControllerdeleteService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.51hHbbT.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\LibroController:index' => ['privates', '.service_locator.Y09RE1E.App\\Controller\\LibroController::index()', 'getLibroControllerindexService', true],
            'App\\Controller\\LibroController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\LibroController::new()', 'getLibroControllernewService', true],
            'App\\Controller\\LibroController:show' => ['privates', '.service_locator.pXPo2Ij.App\\Controller\\LibroController::show()', 'getLibroControllershowService', true],
            'App\\Controller\\LibroController:edit' => ['privates', '.service_locator.8IPZHA6.App\\Controller\\LibroController::edit()', 'getLibroControllereditService', true],
            'App\\Controller\\LibroController:delete' => ['privates', '.service_locator.8IPZHA6.App\\Controller\\LibroController::delete()', 'getLibroControllerdeleteService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.51hHbbT.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\LibroController::index' => '?',
            'App\\Controller\\LibroController::new' => '?',
            'App\\Controller\\LibroController::show' => '?',
            'App\\Controller\\LibroController::edit' => '?',
            'App\\Controller\\LibroController::delete' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\LibroController:index' => '?',
            'App\\Controller\\LibroController:new' => '?',
            'App\\Controller\\LibroController:show' => '?',
            'App\\Controller\\LibroController:edit' => '?',
            'App\\Controller\\LibroController:delete' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.S9s.msl'])) {
            return $container->privates['.service_locator.S9s.msl'];
        }

        return $container->privates['.service_locator.S9s.msl'] = $instance;
    }
}
