<?php

namespace ContainerI413iKI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8IPZHA6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8IPZHA6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'libro' => ['privates', '.errored..service_locator.8IPZHA6.App\\Entity\\Libro', NULL, 'Cannot autowire service ".service_locator.8IPZHA6": it needs an instance of "App\\Entity\\Libro" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'libro' => 'App\\Entity\\Libro',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.8IPZHA6'])) {
            return $container->privates['.service_locator.8IPZHA6'];
        }

        return $container->privates['.service_locator.8IPZHA6'] = $instance;
    }
}
