<?php

namespace ContainerI413iKI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLibroControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y09RE1E.App\Controller\LibroController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y09RE1E.App\\Controller\\LibroController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'libroRepository' => ['privates', 'App\\Repository\\LibroRepository', 'getLibroRepositoryService', true],
        ], [
            'libroRepository' => 'App\\Repository\\LibroRepository',
        ]))->withContext('App\\Controller\\LibroController::index()', $container);
    }
}
