<?php

namespace ContainerI413iKI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLibro2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pXPo2Ij.App\Entity\Libro' shared service.
     *
     * @return \App\Entity\Libro
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.pXPo2Ij": it needs an instance of "App\\Entity\\Libro" but this type has been excluded in "config/services.yaml".');
    }
}
