<?php

namespace ContainerI413iKI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLibroControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pXPo2Ij.App\Controller\LibroController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pXPo2Ij.App\\Controller\\LibroController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'libro' => ['privates', '.errored..service_locator.pXPo2Ij.App\\Entity\\Libro', NULL, 'Cannot autowire service ".service_locator.pXPo2Ij": it needs an instance of "App\\Entity\\Libro" but this type has been excluded in "config/services.yaml".'],
        ], [
            'libro' => 'App\\Entity\\Libro',
        ]))->withContext('App\\Controller\\LibroController::show()', $container);
    }
}
