<?php

namespace ContainerI413iKI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLibroControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8IPZHA6.App\Controller\LibroController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.8IPZHA6'] ?? $container->load('get_ServiceLocator_8IPZHA6Service'));

        if (isset($container->privates['.service_locator.8IPZHA6.App\\Controller\\LibroController::edit()'])) {
            return $container->privates['.service_locator.8IPZHA6.App\\Controller\\LibroController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\LibroController::edit()', $container);

        if (isset($container->privates['.service_locator.8IPZHA6.App\\Controller\\LibroController::edit()'])) {
            return $container->privates['.service_locator.8IPZHA6.App\\Controller\\LibroController::edit()'];
        }

        return $container->privates['.service_locator.8IPZHA6.App\\Controller\\LibroController::edit()'] = $instance;
    }
}
